stages:
  - build
  - deploy
  - prod

variables:
  #DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  #DOCKER_LATEST: $CI_REGISTRY_IMAGE:latest
  HARBOR_REGISTRY: 10.100.93.6:81
  PROJECT_NAME: laravel_project
  DOCKER_IMAGE: $HARBOR_REGISTRY/$PROJECT_NAME/laravel-app:$CI_COMMIT_SHA
  DOCKER_LATEST: $HARBOR_REGISTRY/$PROJECT_NAME/laravel-app:latest
  # ========== building ... ==========
build:
  stage: build
  tags:
    - ci
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - echo "Harbro Registry:" $HARBOR_REGISTRY
    - echo "Project:" $PROJECT_NAME
    - echo "Commit:" $CI_COMMIT_SHA
    - echo "Logging into Registry HARBOR"
    - docker login -u "$HARBOR_USERNAME" -p "$HARBOR_PASSWORD" "$HARBOR_REGISTRY"
  script:
    - echo " ..... Building the Image .... $CI_COMMIT_REF_NAME ...."
    - docker build -f Dockerfile.prod -t $DOCKER_IMAGE .
    - docker tag $DOCKER_IMAGE $DOCKER_LATEST
    - echo "Sending to registry..."
    - docker push $DOCKER_IMAGE
    - docker push $DOCKER_LATEST
    - echo "............. Building Complete! ....................."
  except:
    - tags

# ========== deploy on test (10.100.93.7) ==========
deploy:
  stage: deploy
  tags:
    - test_deploy
  script:
    - echo "Deploy on TEST server ..."
    - echo "Server:" $(hostname)
    - echo "Branch:" $CI_COMMIT_REF_NAME
    - echo "Downloading the image:" $DOCKER_IMAGE
    - echo $HARBOR_PASSWORD | docker login -u $HARBOR_USERNAME --password-stdin $HARBOR_REGISTRY
    - docker pull $DOCKER_IMAGE
    - docker stop laravel-blog-test || true
    - docker rm laravel-blog-test || true
    - docker volume create laravel-test-db || true
    - docker run -d --name laravel-blog-test --restart unless-stopped -p 8080:80 -v laravel-test-db:/var/www/html/database $DOCKER_IMAGE
    - sleep 10
    - docker ps | grep laravel-blog-test
    - echo "Deploy on Test Env Done ! http://10.100.93.7:8080"
  needs:
    - build
  only:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^develop.*/

# ========== PRODUCTION (10.100.93.6) ========== 
prod:
  stage: prod
  tags:
    - prod-only
  script:
    - echo "PRODUCTION DEPLOYMENT"
    - echo "Only from master branch"
    - echo "Server:" $(hostname)
    - docker login -u "$HARBOR_USERNAME" -p "$HARBOR_PASSWORD" "$HARBOR_REGISTRY"
    - docker pull $DOCKER_IMAGE
    - docker stop laravel-blog-prod || true
    - docker rm laravel-blog-prod || true
    - docker volume create laravel-prod-db || true
    - docker run -d --name laravel-blog-prod --restart unless-stopped -p 8080:80 -v laravel-prod-db:/var/www/html/database $DOCKER_IMAGE
    - sleep 10
    - docker ps | grep laravel-blog-prod
    - echo "PRODUCTION finished"
    - echo "http://10.100.93.6:8080"
  needs:
    - build
  only:
    - master
