---
# Установка зависимостей для сборки модулей и самого nginx
- name: Install build dependencies
  apt:
    name:
      - git                  # Для клонирования репозиториев
      - g++                  # Компилятор C++
      - make                 # Сборщик проектов
      - automake             # Автоматизация сборки
      - libtool              # Поддержка создания библиотек
      - pkg-config           # Утилита для поиска библиотек
      - libpcre3-dev         # Для regexp в nginx
      - libxml2              # XML-парсер, нужен ModSecurity
      - libxml2-dev          # dev-пакет для сборки
      - libyajl-dev          # Для работы с JSON в ModSecurity
      - libcurl4-openssl-dev # Для HTTP/HTTPS запросов (ModSecurity)
      - libgeoip-dev         # Для geoip (старый, но иногда нужен)
      - liblmdb-dev          # Для быстрой работы с БД (ModSecurity)
      - libssl-dev           # Для поддержки SSL в nginx и модулях
      - libxml2-utils        # Утилиты XML (может понадобиться)
      - libpcre2-dev         # Для regexp (более новая версия)
      - build-essential      # Стандартный набор для сборки
      - gcc                  # C компилятор
      - zlib1g               # Архивация (gzip)
      - zlib1g-dev           # dev-пакет для сборки модулей
      - libmaxminddb0        # Для GeoIP2 (runtime)
      - libmaxminddb-dev     # Для GeoIP2 (build)
      - mmdb-bin             # Для работы с MaxMind .mmdb
    state: present
    update_cache: yes

# Устанавливаем сам Nginx через apt
- name: Install nginx from apt
  apt:
    name: nginx
    state: present

# Проверяем, что nginx установлен и выводим его версию
- name: Show nginx version
  command: nginx -v
  register: nginx_version
  ignore_errors: yes  # чтобы не валился, если nginx не стартует

- name: Print nginx version output
  debug:
    msg: "{{ nginx_version.stderr }}"
