apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: production
type: Opaque
stringData:
  postgres-password: PostgresAdmin123
  app-db-name: applicationdb
  app-user: appuser
  app-password: AppUser456