all:
  hosts:
    prx01:
      ansible_host: 10.100.93.3
    prx02:
      ansible_host: 10.100.93.4
    app01:
      ansible_host: 10.100.93.5
    app02:
      ansible_host: 10.100.93.6
    app03:
      ansible_host: 10.100.93.7
    db01:
      ansible_host: 10.100.93.8
  vars:
    ansible_user: scusnir
    ansible_ssh_private_key_file: ~/.ssh/id_rsa_scusnir
    ansible_python_interpreter: /usr/bin/python3
