apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prod-pattern
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pattern
  template:
    metadata:
      labels:
        app: nginx-pattern
    spec:
      containers:
      - name: nginx-prod-pattern
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
