# nginx-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: production
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        server {
            listen 80;
            location / {
                return 200 'Production Nginx - Healthy\n';
                add_header Content-Type text/plain;
            }
            location /health {
                return 200 'OK';
                add_header Content-Type text/plain;
            }
        }
    }
