---
- name: Полное удаление Nginx и всех остатков
  hosts: all
  become: yes

  tasks:
    - name: Остановить сервис nginx (не выводить ошибку, если сервиса нет)
      ansible.builtin.systemd:
        name: nginx
        state: stopped
      ignore_errors: yes

    - name: Отключить сервис nginx (не выводить ошибку, если сервиса нет)
      ansible.builtin.systemd:
        name: nginx
        enabled: no
      ignore_errors: yes

    - name: Удалить пакеты nginx полностью (purge)
      ansible.builtin.apt:
        name:
          - nginx
          - nginx-common
          - nginx-full
        state: absent
        purge: yes
        update_cache: yes

    - name: Удалить неиспользуемые зависимости
      ansible.builtin.apt:
        autoremove: yes

    - name: Удалить все каталоги nginx (если существуют)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/nginx
        - /var/log/nginx
        - /var/cache/nginx
        - /usr/lib/nginx
        - /usr/share/nginx
        - /var/www/html
        - /usr/local/src/ModSecurity-nginx/.github/nginx
      ignore_errors: yes

    - name: Очистить apt-кэш
      ansible.builtin.command: apt clean
      changed_when: false

    - name: Попробовать убить оставшиеся процессы nginx (не выводить ошибку, если их нет)
      ansible.builtin.shell: |
        if pgrep nginx; then
          pkill -f nginx
        fi
      args:
        warn: false
      ignore_errors: yes

    - name: Поиск остаточных файлов nginx (выводит только для информации)
      ansible.builtin.shell: "find / -name '*nginx*' | grep -v 'filebeat/module/nginx' || true"
      register: nginx_leftovers
      changed_when: false

    - name: Вывести список найденных остатков (информативно)
      ansible.builtin.debug:
        var: nginx_leftovers.stdout_lines
